# QiLifeStore Social Media Engagement Bot - Credentials Example
# IMPORTANT: Copy this file to credentials.yml and fill in your actual credentials
# DO NOT commit your actual credentials.yml file to version control

# Reddit API credentials
# Instructions: Create an app at https://www.reddit.com/prefs/apps
reddit:
  client_id: "HhgilX3v20MsMgU9AakDHw"
  client_secret: "Q8oHRuzJRg-rpKj_60nMEiceoOeAQQ"
  username: "VariationInfinite682"
  password: "100669@@Aa"
  user_agent: "QiLifeStore Socialmedia v1.0 /u/VariationInfinite682"

# Quora credentials
# Note: Quora doesn't have an official API, so we use browser automation
quora:
  username: "vajoy77382@lushosa.com"
  password: "100669@@Aa"
  
# URL shortener API (optional, for analytics)
url_shortener:
  enabled: false
  provider: "bitly"  # Supported: bitly, tinyurl
  api_key: "YOUR_URL_SHORTENER_API_KEY" 